In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import string
import scipy as sp
import seaborn as sns
import time
%matplotlib inline

import pickle

In [3]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler = StandardScaler()
minmax = MinMaxScaler()

In [4]:
data = pd.read_csv('final_dataset3.csv',index_col=0)
# data2 = pd.read_csv('final_dataset2.csv',index_col=0)
# data['count'] = data2['count']
# data['class'] = data['class'].replace([0],1)

In [5]:
data.head(100)

class  scale  Pos  Neg  binary  QuestionMarkCount  QuotationMarkCount  \
0       1     -1    1   -2      -1                  0                   1   
1       0     -2    1   -3      -1                  0                   0   
2       0     -2    2   -4      -1                  1                   0   
3       0      1    2   -1       1                  0                   0   
4       0      0    2   -2       1                  0                   0   
..    ...    ...  ...  ...     ...                ...                 ...   
95      0     -1    1   -2      -1                  0                   0   
96      0     -2    1   -3      -1                  0                   0   
97      0     -1    1   -2      -1                  0                   0   
98      0      1    2   -1       1                  0                   1   
99      0      1    2   -1       1                  0                   0   

    ExclamationMarkCount  AllCapitalised  bitch  ...  xxx  #sex  #xxx  blow  \
0                      0               0      0  ...    0     0     0     0   
1                      2               0      0  ...    0     0     0     0   
2                      0               0      1  ...    0     0     0     0   
3                      0               0      0  ...    0     0     0     0   
4                      0               0      1  ...    0     0     0     0   
..                   ...             ...    ...  ...  ...   ...   ...   ...   
95                     0               0      0  ...    0     0     0     0   
96                     0               0      1  ...    0     0     0     0   
97                     0               0      0  ...    0     0     0     0   
98                     0               0      0  ...    0     0     0     0   
99                     4               0      0  ...    0     0     0     0   

    mother  drug  rap  sexi  lip  thick  
0        0     0    0     0    0      0  
1        0     0    0     0    0      0  
2        0     0    0     0    0      0  
3        0     0    0     0    0      0  
4        0     0    0     0    0      0  
..     ...   ...  ...   ...  ...    ...  
95       0     0    0     0    0      0  
96       0     0    0     0    0      0  
97       0     0    0     0    0      0  
98       0     0    0     0    0      0  
99       0     0    0     0    0      0  

[100 rows x 146 columns]

In [6]:
# data = data.drop(['Pos','Neg','binary'],axis=1)
columns = data.columns

In [7]:
print(columns)

Index(['class', 'scale', 'Pos', 'Neg', 'binary', 'QuestionMarkCount',
       'QuotationMarkCount', 'ExclamationMarkCount', 'AllCapitalised', 'bitch',
       ...
       'xxx', '#sex', '#xxx', 'blow', 'mother', 'drug', 'rap', 'sexi', 'lip',
       'thick'],
      dtype='object', length=146)


In [8]:
print(data.head())
data.describe

   class  scale  Pos  Neg  binary  QuestionMarkCount  QuotationMarkCount  \
0      1     -1    1   -2      -1                  0                   1   
1      0     -2    1   -3      -1                  0                   0   
2      0     -2    2   -4      -1                  1                   0   
3      0      1    2   -1       1                  0                   0   
4      0      0    2   -2       1                  0                   0   

   ExclamationMarkCount  AllCapitalised  bitch  ...  xxx  #sex  #xxx  blow  \
0                     0               0      0  ...    0     0     0     0   
1                     2               0      0  ...    0     0     0     0   
2                     0               0      1  ...    0     0     0     0   
3                     0               0      0  ...    0     0     0     0   
4                     0               0      1  ...    0     0     0     0   

   mother  drug  rap  sexi  lip  thick  
0       0     0    0     0    0  

<bound method NDFrame.describe of        class  scale  Pos  Neg  binary  QuestionMarkCount  QuotationMarkCount  \
0          1     -1    1   -2      -1                  0                   1   
1          0     -2    1   -3      -1                  0                   0   
2          0     -2    2   -4      -1                  1                   0   
3          0      1    2   -1       1                  0                   0   
4          0      0    2   -2       1                  0                   0   
...      ...    ...  ...  ...     ...                ...                 ...   
40285      1      2    3   -1       1                  0                   0   
40286      1      1    2   -1       1                  1                   2   
40287      1     -1    1   -2      -1                  0                   0   
40288      1      0    1   -1       1                  0                   0   
40289      1      2    3   -1       1                  0                   0   

     

In [9]:
X = data[columns[1:]].to_numpy()
X = minmax.fit_transform(X)
y = data['class'].to_numpy()

In [10]:
print(X)

[[0.375 0.    0.75  ... 0.    0.    0.   ]
 [0.25  0.    0.5   ... 0.    0.    0.   ]
 [0.25  0.25  0.25  ... 0.    0.    0.   ]
 ...
 [0.375 0.    0.75  ... 0.    0.    0.   ]
 [0.5   0.    1.    ... 0.    0.    0.   ]
 [0.75  0.5   1.    ... 0.    0.    0.   ]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,stratify=data['class'])

In [12]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=40, random_state=0)

In [13]:
%time clf.fit(X_train, y_train)

Wall time: 5 s


RandomForestClassifier(max_depth=40, random_state=0)

In [14]:
%time Score = clf.score(X_test,y_test)
print(Score*100)

Wall time: 148 ms
96.72375279225615


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, cohen_kappa_score

In [16]:
%time y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy', accuracy_score(y_test, y_pred) * 100)
print(classification_report(y_test, y_pred))
print('Cohen Kappa score:', cohen_kappa_score(y_test, y_pred))

Wall time: 141 ms
[[3921  203]
 [  61 3873]]
Accuracy 96.72375279225615
              precision    recall  f1-score   support

           0       0.98      0.95      0.97      4124
           1       0.95      0.98      0.97      3934

    accuracy                           0.97      8058
   macro avg       0.97      0.97      0.97      8058
weighted avg       0.97      0.97      0.97      8058

Cohen Kappa score: 0.9344930741589769


In [17]:
print(y_pred)

[0 0 1 ... 0 1 0]


In [18]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
st = time.time()
lr.fit(X_train,y_train)
et = time.time()
print(et-st)
%time y_pred=lr.predict(X_train)
print(confusion_matrix(y_train, y_pred))
print('Accuracy', accuracy_score(y_train, y_pred) * 100)
print(classification_report(y_train, y_pred))
print('Cohen Kappa score:', cohen_kappa_score(y_train, y_pred))

0.5263233184814453
Wall time: 6.98 ms
[[15612   884]
 [  230 15506]]
Accuracy 96.54380739637627
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     16496
           1       0.95      0.99      0.97     15736

    accuracy                           0.97     32232
   macro avg       0.97      0.97      0.97     32232
weighted avg       0.97      0.97      0.97     32232

Cohen Kappa score: 0.9309038475281197


In [19]:
X.shape

(40290, 145)

In [20]:
Pkl_Filename = "ternary_model.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(lr, file)
  


In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
%time knn.fit(X_train,y_train)

CPU times: user 1.21 s, sys: 8.55 ms, total: 1.22 s
Wall time: 1.22 s


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [21]:
%time y_pred = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy', accuracy_score(y_test, y_pred) * 100)
print(classification_report(y_test, y_pred))
print('Cohen Kappa score:', cohen_kappa_score(y_test, y_pred))

CPU times: user 10.4 s, sys: 41.2 ms, total: 10.4 s
Wall time: 10.4 s
[[  60  166   60]
 [  60 3619  399]
 [   6   72 2656]]
Accuracy 89.25049309664695
              precision    recall  f1-score   support

           0       0.48      0.21      0.29       286
           1       0.94      0.89      0.91      4078
           2       0.85      0.97      0.91      2734

    accuracy                           0.89      7098
   macro avg       0.76      0.69      0.70      7098
weighted avg       0.89      0.89      0.89      7098

Cohen Kappa score: 0.7925015609008812


In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
gnb = GaussianNB()
%time model = gnb.fit(X_train, y_train)

CPU times: user 60.2 ms, sys: 35.4 ms, total: 95.7 ms
Wall time: 96.1 ms


In [24]:
%time y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy', accuracy_score(y_test, y_pred) * 100)

CPU times: user 22.8 ms, sys: 7.13 ms, total: 30 ms
Wall time: 28.5 ms
[[ 234   10   42]
 [3379  348  351]
 [ 156   26 2552]]
Accuracy 44.15328261482108


In [25]:
print(classification_report(y_test, y_pred))
print('Cohen Kappa score:', cohen_kappa_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.06      0.82      0.12       286
           1       0.91      0.09      0.16      4078
           2       0.87      0.93      0.90      2734

    accuracy                           0.44      7098
   macro avg       0.61      0.61      0.39      7098
weighted avg       0.86      0.44      0.44      7098

Cohen Kappa score: 0.2910243005055071


In [26]:
from sklearn.metrics import accuracy_score, log_loss
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis


In [27]:
classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="rbf", C=0.025, probability=True),
#     NuSVC(probability=True),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    GaussianNB(),
    LinearDiscriminantAnalysis(),
    QuadraticDiscriminantAnalysis()]

In [28]:
log_cols=["Classifier", "Accuracy", "Log Loss"]
log = pd.DataFrame(columns=log_cols)

for clf in classifiers:
    clf.fit(X_train, y_train)
    name = clf.__class__.__name__
    
    print("="*30)
    print(name)
    
    print('****Results****')
    train_predictions = clf.predict(X_test)
    acc = accuracy_score(y_test, train_predictions)
    print("Accuracy: {:.4%}".format(acc))
    
    train_predictions = clf.predict_proba(X_test)
    ll = log_loss(y_test, train_predictions)
    print("Log Loss: {}".format(ll))
    
    log_entry = pd.DataFrame([[name, acc*100, ll]], columns=log_cols)
    log = log.append(log_entry)
    
print("="*30)

DecisionTreeClassifier
****Results****
Accuracy: 87.2218%
Log Loss: 2.5486950267270774
RandomForestClassifier
****Results****
Accuracy: 88.9828%
Log Loss: 0.6523806424258477
AdaBoostClassifier
****Results****
Accuracy: 89.5604%
Log Loss: 1.032948677958362
GradientBoostingClassifier
****Results****
Accuracy: 89.5464%
Log Loss: 0.3282188915237278
GaussianNB
****Results****
Accuracy: 44.1533%
Log Loss: 18.723625718017775
LinearDiscriminantAnalysis
****Results****
Accuracy: 88.5461%
Log Loss: 0.5206582522934258


/usr/local/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis
****Results****
Accuracy: 41.9696%
Log Loss: 19.989812463299078
